<?php 
error_reporting(E_ALL);
session_start();
$api_token = <<<xxx
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImI5YmZhZDQwLTBhZTEtNGRlNi1iYTlmLTg5ODU2ZDcwMGM2NiIsImlhdCI6MTUzNzE4OTMxMywic3ViIjoiZGV2ZWxvcGVyL2E3NWY2MzQ2LWU2MTAtZmEzNi1jYWE2LWVlMWE0OThmYzUyZiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjUyLjIyMS4xODYuNjIiLCIxMjAuMjkuMTEyLjIzMiJdLCJ0eXBlIjoiY2xpZW50In1dfQ.Furky-FxP3kNRpMCIrapQkVxGdO_n19nuhk3V728El3Vp6bS_3n4vSFrOk1d38Fm7OA3z2yhwMi27xD5YfjRJw
xxx;

define("API_TOKEN", $api_token);
define("db_user","root");
define("db_host","localhost");
define("db_name","ocwfest");
define("db_password","kai_sean1");


